#! /bin/sh

echo "Checking Assignment 4 Solutions" > results.txt

echo "" >> results.txt

echo "======= Generating query output =======" >> results.txt

# checking queries
for query in q1 q2 q3 q4 q5 q6 q7 q8 q9 q10
do
   echo "" >> results.txt
   echo "--- Query" $query "---" >> results.txt
   echo "" >> results.txt
   echo "Raw results:" >> results.txt
   galax-run $query.xq >> results.txt 2>&1
done

# The queries we can use xmllint to "pretty print" 
# (because we have a dtd).
#for query in q6 q7 q8
#do
#   echo "" >> results.txt
#   echo "--- Query" $query "---" >> results.txt
#   echo "" >> results.txt
#   echo "Raw results:" >> results.txt
#   galax-run $query.xq >> results.txt  2>&1
#   echo "<?xml version='1.0' standalone='no' ?>" > TEMP.xml
#   galax-run $query.xq >> TEMP.xml  2>&1
#   echo "" >> results.txt
#   echo "Pretty results:" >> results.txt
#   xmllint --format TEMP.xml >> results.txt  2>&1
# done


echo "" >> results.txt
echo "======= Validating xml generated by queries =======" >> results.txt

echo "" >> results.txt
echo "--- Query" q9 "---" >> results.txt
echo "<?xml version='1.0' standalone='no' ?>" > TEMP.xml
echo "<!DOCTYPE Stats SYSTEM 'stats.dtd'>" >> TEMP.xml
galax-run q9.xq >> TEMP.xml  2>&1
echo "Results well-formed?" >> results.txt
xmllint --format TEMP.xml >> results.txt  2>&1
echo "" >> results.txt
echo "Results valid?" >> results.txt
xmllint --noout --format --dtdvalid stats.dtd TEMP.xml >> results.txt

echo "" >> results.txt
echo "--- Query" q10 "---" >> results.txt
echo "<?xml version='1.0' standalone='no' ?>" > TEMP.xml
echo "<!DOCTYPE Actress SYSTEM 'actressinfo.dtd'>" >> TEMP.xml
galax-run q10.xq >> TEMP.xml  2>&1
echo "Results well-formed?" >> results.txt
xmllint --format TEMP.xml >> results.txt  2>&1
echo "" >> results.txt
echo "Results valid?" >> results.txt
xmllint --noout --format --dtdvalid actressinfo.dtd TEMP.xml >> results.txt
